Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-9"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

  config.vm.define "m1" do |m1|
    m1.vm.network "private_network", ip: "10.24.60.10"
  end

  config.vm.define "m2" do |m2|
    m2.vm.network "private_network", ip: "10.24.60.20"
  end

  config.vm.define "n1" do |n1|
    n1.vm.network "private_network", ip: "10.24.70.10"
  end

  config.vm.define "n2" do |n2|
    n2.vm.network "private_network", ip: "10.24.70.20"
  end
end

